version: "3"

services:

  lavalink:
    image: fredboat/lavalink:dev
    container_name: lavalink
    ports:
      - "8000:8000"
    hostname: lavalink
    restart: unless-stopped
    volumes:
      - /root/lavalink/application.yml:/opt/Lavalink/application.yml:ro
